replicaCount: 1

image:
  pullPolicy: IfNotPresent

envEnabled: true
env:
- name: "NODE_ENV"
  value: "dev"
- name: "TZ"
  value: America/Sao_Paulo
- name: "ELASTIC_APM_SERVER_URL"
  value: "http://172.20.89.206:8200"
- name: "ELASTIC_APM_SERVICE_NAME"
  value: "K8S_FIANCA_ENVIAR_CARTA_PARECER_CREDITO_SVC"
- name: "ELASTIC_APM_ENVIRONMENT"
  value: "development"
- name: "AWS_REGION"
  value: "us-east-2"
- name: "AWS_ACCESS_KEY_ID"
  value: "AKIA4MWJJC2MOGVSASJH"
- name: "AWS_SQS_MICROSERVICE_QUEUE_URL"
  value: "https://sqs.us-east-2.amazonaws.com/851899389592/fianca-enviar-carta-parecer-credito"
- name: "AWS_SQS_MICROSERVICE_QUEUE_NAME"
  value: "fianca-enviar-carta-parecer-credito"

secretEnabled: true
secret:
- name: "AWS_SECRET_ACCESS_KEY"
  key: "AWS_SECRET_ACCESS_KEY"

resource:
  limits:
    memory: 512Mi
    cpu: 300m

autoscaling:
  enabled: true
  minReplicas: 0
  maxReplicas: 10
  SQS:
    enabled: true
    pollingInterval: 5
    queueURL: "https://sqs.us-east-2.amazonaws.com/851899389592/fianca-enviar-carta-parecer-credito"
    targetMessages: 1
    awsRegion: "us-east-2"